labels:
  issue: 'type:issue'
  'pull-request': 'type:pull-request'
release:
  trigger:
    title: '^chore: release'
    labels:
      - 'release'
  checklist: |
    # Release checklist 🚀
    
      - [ ] Some item
    
